// <auto-generated />
using System;
using EFModels.LogsDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EFModels.Migrations.LogDBMigrations
{
    [DbContext(typeof(LogDBContext))]
    [Migration("20200518145528_ActivityNameFix")]
    partial class ActivityNameFix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EFModels.LogsDB.EventLog", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Activity")
                        .HasColumnType("text");

                    b.Property<bool>("AnalysStatus")
                        .HasColumnType("boolean");

                    b.Property<long>("CaseId")
                        .HasColumnType("bigint");

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<string>("Resourse")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("EventId");

                    b.ToTable("EventLogs");
                });

            modelBuilder.Entity("EFModels.LogsDB.EventLog", b =>
                {
                    b.OwnsOne("EFModels.LogsDB.EventLogData", "eventLogData", b1 =>
                        {
                            b1.Property<long>("eventLogEventId")
                                .HasColumnType("bigint");

                            b1.Property<string>("ActivityText")
                                .HasColumnType("text");

                            b1.Property<string>("ActivityText2")
                                .HasColumnType("text");

                            b1.Property<long>("EventId")
                                .HasColumnType("bigint");

                            b1.Property<string>("ResourseDepartment")
                                .HasColumnType("text");

                            b1.Property<string>("ResourseFIO")
                                .HasColumnType("text");

                            b1.Property<string>("ResourseFilial")
                                .HasColumnType("text");

                            b1.HasKey("eventLogEventId");

                            b1.ToTable("EventLogDatas");

                            b1.WithOwner("eventLog")
                                .HasForeignKey("eventLogEventId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
