using Controller;
using System;
using System.Collections.ObjectModel;
using System.Windows;
using System.Windows.Controls;

namespace UI
{
    public partial class Alerts : Window
    {
        public ObservableCollection<LogDTO> logs = new ObservableCollection<LogDTO>();
        public Alerts()
        {
            InitializeComponent();

            AlertDTOs _tasks = (AlertDTOs)this.Resources["tasks"];

            _tasks = new AlertsControl().GetAlerts(_tasks);
        }

        private void dataGrid1_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dataGrid1.Columns[0].Visibility = Visibility.Collapsed;
            dataGrid1.Columns[1].Visibility = Visibility.Collapsed;
            dataGrid1.ColumnWidth = DataGridLength.SizeToCells;

        }

        private void dataGrid1_AutoGeneratingColumn(object sender, System.Windows.Controls.DataGridAutoGeneratingColumnEventArgs e)
        {
            e.Column.Width = new DataGridLength(1, DataGridLengthUnitType.Auto);
        }
    }
}
