using Controller;
using System;
using System.Collections.ObjectModel;
using System.Windows;
using System.Windows.Controls;

namespace UI
{
    /// <summary>
    /// Логика взаимодействия для Logs.xaml
    /// </summary>
    public partial class Logs : Window
    {
        public ObservableCollection<LogDTO> logs = new ObservableCollection<LogDTO>();
        private LogsControl LogsControl = new LogsControl();
        public Logs()
        {
            InitializeComponent();

            LogDTOs _tasks = (LogDTOs)this.Resources["tasks"];
            _tasks = LogsControl.GetLogs(_tasks);
        }

        private void dataGrid1_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dataGrid1.Columns[0].Visibility = Visibility.Collapsed;
            dataGrid1.Columns[1].Visibility = Visibility.Collapsed;
            dataGrid1.Columns[2].Visibility = Visibility.Collapsed;
            dataGrid1.ColumnWidth = DataGridLength.SizeToCells;
            
        }

        private void dataGrid1_AutoGeneratingColumn(object sender, System.Windows.Controls.DataGridAutoGeneratingColumnEventArgs e)
        {
            e.Column.Width = new DataGridLength(1, DataGridLengthUnitType.Auto);
        }

        private void OpenBP_Click(object sender, RoutedEventArgs e)
        {
            //if (dataGrid1.SelectedItem != null)
            //{
            //    LogDTO log = dataGrid1.SelectedItem as LogDTO;
            //    new BPs(mainDB.BPs.Single(s=>s.Name==log.БП).Id).ShowDialog();
            //}
        }
    }
}
